AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "Gemfile"

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
